// @generated by protoc-gen-es v1.3.0 with parameter "target=ts"
// @generated from file services/migrations/prismConnection.proto (package services.migrations, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { ErrorMessage } from "../utils/error_pb.js";

/**
 * @generated from message services.migrations.GenerateMigrationsResponse
 */
export class GenerateMigrationsResponse extends Message<GenerateMigrationsResponse> {
  /**
   * @generated from field: services.utils.ErrorMessage Error = 1;
   */
  Error?: ErrorMessage;

  /**
   * @generated from field: string status = 2;
   */
  status = "";

  constructor(data?: PartialMessage<GenerateMigrationsResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "services.migrations.GenerateMigrationsResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "Error", kind: "message", T: ErrorMessage },
    { no: 2, name: "status", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenerateMigrationsResponse {
    return new GenerateMigrationsResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenerateMigrationsResponse {
    return new GenerateMigrationsResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenerateMigrationsResponse {
    return new GenerateMigrationsResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GenerateMigrationsResponse | PlainMessage<GenerateMigrationsResponse> | undefined, b: GenerateMigrationsResponse | PlainMessage<GenerateMigrationsResponse> | undefined): boolean {
    return proto3.util.equals(GenerateMigrationsResponse, a, b);
  }
}

/**
 * @generated from message services.migrations.GenerateMigrationsRequest
 */
export class GenerateMigrationsRequest extends Message<GenerateMigrationsRequest> {
  constructor(data?: PartialMessage<GenerateMigrationsRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "services.migrations.GenerateMigrationsRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenerateMigrationsRequest {
    return new GenerateMigrationsRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenerateMigrationsRequest {
    return new GenerateMigrationsRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenerateMigrationsRequest {
    return new GenerateMigrationsRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GenerateMigrationsRequest | PlainMessage<GenerateMigrationsRequest> | undefined, b: GenerateMigrationsRequest | PlainMessage<GenerateMigrationsRequest> | undefined): boolean {
    return proto3.util.equals(GenerateMigrationsRequest, a, b);
  }
}

